spring:
  config:
    import: "classpath:.env.properties"
  application:
    name: InterStory

#  ?? aws RDB ???
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:// { }.ap-northeast-2.rds.amazonaws.com:3306/salty_db?serverTimezone=Asia/Seoul
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_second_level_cache: false
        use_query_cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: khsso102649@gmail.com
    password: yjuikbjezgbyosyw
    properties:
      mail:
        smtp:
          auth: true
          required: true
        connection timeout: 5000
        timeout: 5000
        write timeout: 5000

  data:
    redis:
      host: localhost
      port: 6379

  aop:
    auto: true
    proxy-target-class: true


kakao:
  client_id: ${KAKAO_CLIENT_ID}
  secret_key: ${KAKAO_CLIENT_SECRET}
  redirect_uri: ${KAKAO_REDIRECT_URI}
  admin_key: ${KAKAO_ADMIN_KEY}


logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: TRACE
    com.app.salty.checklist: DEBUG
    org.springframework.web: DEBUG


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: est-team5-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 8080





